version: '3.9'
services:
  postgres:
    image: debezium/example-postgres
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=password
     
  debezium-server:
    image: debezium/server
    container_name: debezium-server
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: PATH_TO_CREDENTIALS
    ports:
      - "8081:8080"
    volumes:
      - PATH_TO_CREDENTIALS
      - ./conf:/debezium/conf

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin_dummy_container
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin.admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin